[package]
name = "mentat-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
mentat = { path = "../../mentat", features = [
  "client",
], default-features = false }
clap = { version = "3.1.8", features = ["derive"] }
futures = "0.3.21"
cli-table = "0.4.6"
chrono = "0.4.19"
